### ISSUE TITLE
Getting a WebsocketError(Url(UnsupportedUrlScheme)) Error when trying to create a new WS client

### ISSUE THREAD

**Issue by TacticalDeux** [AlsoSylv/Irelia#7]
Just simply calling
```rs
let mut ws_client = ws::LCUWebSocket::new().await?;
```
makes it Err

**Comment by AlsoSylv** [comment]
This will be fixed in the next release, for now depends on git should be stable enough, and I'll try to get a 0.3.1 out by this weekend!

**Comment by AlsoSylv** [comment]
0.3.1 is on crates.io now!
